age <- c(23, 23, 27, 27, 39, 41, 47, 49, 50, 52, 54, 54, 56, 57, 58, 58, 60, 61)
fat <- c(9.5, 26.5, 7.8, 17.8, 31.4, 25.9, 27.4, 27.2, 31.2, 34.6, 42.5, 28.8, 33.4, 30.2, 34.1, 32.9, 41.2, 35.7)
mean_age <- mean(age)
median_age <- median(age)
sd_age <- sd(age)
mean_fat <- mean(fat)
median_fat <- median(fat)
sd_fat <- sd(fat)
print(paste("Mean Age:", mean_age))
print(paste("Median Age:", median_age))
print(paste("Standard Deviation of Age:", sd_age))̥
print(paste("Mean %Fat:", mean_fat))
print(paste("Median %Fat:", median_fat))
print(paste("Standard Deviation of %Fat:", sd_fat))
par(mfrow = c(1,2))
boxplot(age, main="Boxplot of Age", col="lightblue")
boxplot(fat, main="Boxplot of %Fat", col="lightgreen")
par(mfrow = c(1,2))
plot(age, fat, main="Scatter Plot of Age vs %Fat", xlab="Age", ylab="%Fat", pch=19, col="blue")
qqnorm(age, main="Q-Q Plot for Age")
qqline(age, col="red")
qqnorm(fat, main="Q-Q Plot for %Fat")
qqline(fat, col="red")
